#!/usr/bin/bash
# /usr/lib/iso/gen-hyprland-config.sh — Generate GPU env + monitor config for Hyprland
# Called by first-boot.sh. Writes GPU env vars to ~/.config/hypr/env/gpu.conf
# and monitor override to ~/.config/hypr/env/monitor.conf.
# The main hyprland.conf sources these via `source =`.
set -euo pipefail

log() { logger -t iso-hyprland "$*"; }

GPU="${1:-$(cat /etc/iso-gpu-driver 2>/dev/null || echo modesetting)}"
USER_HOME="/home/aiuser"
ENV_DIR="$USER_HOME/.config/hypr/env"
mkdir -p "$ENV_DIR"

MONITOR_NAME=""
RESOLUTION="1920x1080"
REFRESH="60"
SCALE="1"

# Try sysfs first (Wayland-safe)
for card in /sys/class/drm/card*-*; do
  if [[ -f "$card/status" ]] && [[ "$(cat "$card/status")" == "connected" ]]; then
    MONITOR_NAME=$(basename "$card" | sed 's/card[0-9]-//')
    if [[ -f "$card/modes" ]]; then
      MODE=$(head -1 "$card/modes" 2>/dev/null || echo "")
      if [[ -n "$MODE" ]]; then
        RESOLUTION=$(echo "$MODE" | cut -d'p' -f1)
        REFRESH=$(echo "$MODE" | grep -oP 'p-\K\d+' || echo "60")
      fi
    fi
    break
  fi
done

# Fallback to xrandr
if [[ -z "$MONITOR_NAME" ]] && command -v xrandr &>/dev/null; then
  MONITOR_INFO=$(DISPLAY=:0 xrandr --query 2>/dev/null | grep -E ' connected' | head -1 || echo "")
  MONITOR_NAME=$(echo "$MONITOR_INFO" | cut -d' ' -f1)
  RESOLUTION=$(echo "$MONITOR_INFO" | grep -oP '\d{3,4}x\d{3,4}' | head -1 || echo "1920x1080")
  REFRESH=$(echo "$MONITOR_INFO" | grep -oP '\d+\.\d+\*' | head -1 | tr -d '*' || echo "60")
fi

# HiDPI via EDID
DPI="96"
for card in /sys/class/drm/card*-*; do
  if [[ -f "$card/edid" ]]; then
    EDID_HEX=$(xxd -p -s 54 -l 2 "$card/edid" 2>/dev/null || echo "")
    if [[ -n "$EDID_HEX" ]]; then
      DPI=$(printf "%d" "$((0x$EDID_HEX))" 2>/dev/null || echo "96")
    fi
    break
  fi
done
if [[ "$DPI" == "96" ]] && command -v xdpyinfo &>/dev/null; then
  DPI=$(DISPLAY=:0 xdpyinfo 2>/dev/null | grep -oP 'resolution:\s+\K\d+' | head -1 || echo "96")
fi

if [[ "$DPI" -gt 144 ]]; then SCALE="2"
elif [[ "$DPI" -gt 120 ]]; then SCALE="1.5"
fi

# GPU env vars
GPU_CONF="$ENV_DIR/gpu.conf"
cat > "$GPU_CONF" << EOF
# GPU environment — auto-generated by gen-hyprland-config.sh
# GPU: ${GPU} | DPI: ${DPI} | Scale: ${SCALE}
EOF

case "$GPU" in
  nvidia)
    cat >> "$GPU_CONF" << 'NVIDIA'
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER,vulkan
env = WLR_DRM_NO_MODIFIERS,1
NVIDIA
    ;;
  amd)
    cat >> "$GPU_CONF" << 'AMD'
env = LIBVA_DRIVER_NAME,radeonsi
env = GBM_BACKEND,gbm
env = WLR_NO_HARDWARE_CURSORS,0
AMD
    ;;
  intel)
    cat >> "$GPU_CONF" << 'INTEL'
env = LIBVA_DRIVER_NAME,i965
env = GBM_BACKEND,gbm
env = WLR_NO_HARDWARE_CURSORS,0
INTEL
    ;;
  *)
    cat >> "$GPU_CONF" << 'FALLBACK'
env = GBM_BACKEND,gbm
env = WLR_NO_HARDWARE_CURSORS,1
FALLBACK
    ;;
esac

# VM performance tuning
PERF_CONF="$ENV_DIR/perf.conf"
if systemd-detect-virt --vm --quiet 2>/dev/null; then
    cp /usr/share/hyprland/performance.conf "$PERF_CONF"
    log "VM detected — applied Hyprland performance tuning"
else
    cat > "$PERF_CONF" << 'NOVM'
# No performance restrictions for bare metal
misc {
    vfr = true
    vrr = 2
}
NOVM
fi

# Monitor config
MONITOR_CONF="$ENV_DIR/monitor.conf"
cat > "$MONITOR_CONF" << EOF
# Monitor config — auto-generated
# Resolution: ${RESOLUTION} @ ${REFRESH}Hz | Scale: ${SCALE}
monitor = ${MONITOR_NAME},${RESOLUTION}@${REFRESH},auto,${SCALE}
EOF

chmod 644 "$GPU_CONF" "$MONITOR_CONF"
chown -R aiuser:aiuser "$ENV_DIR"

log "Hyprland config generated for GPU=$GPU, DPI=$DPI, Scale=$SCALE"
