#!/usr/bin/env bash
# /usr/lib/iso/hyprland-gpu-detect.sh
# System-wide GPU detection for Hyprland.
# Called by hyprland-setup.sh as fallback if user script doesn't exist.

set -euo pipefail

detect_vm() {
  if systemd-detect-virt --vm --quiet 2>/dev/null; then return 0; fi
  if grep -qi "hypervisor" /proc/cpuinfo 2>/dev/null; then return 0; fi
  return 1
}

detect_gpu() {
  local gpu_info
  gpu_info=$(lspci 2>/dev/null | grep -iE "(vga|3d|display)" || echo "")
  if echo "$gpu_info" | grep -qi "nvidia"; then echo "nvidia"
  elif echo "$gpu_info" | grep -qi "amd\|advanced micro devices"; then echo "amd"
  elif echo "$gpu_info" | grep -qi "intel"; then echo "intel"
  elif echo "$gpu_info" | grep -qi "virtio\|qxl\|cirrus\|vmware\|vbox"; then echo "vm"
  else echo "unknown"
  fi
}

GPU_CONF="$HOME/.config/hypr/env/gpu.conf"
mkdir -p "$(dirname "$GPU_CONF")"

GPU=$(detect_gpu)
VM=false
detect_vm && VM=true

{
  echo "# GPU environment variables — auto-generated by hyprland-gpu-detect.sh"
  echo "# This file is sourced by hyprland.conf"
  echo ""

  case "$GPU" in
    nvidia)
      echo "env = WLR_NO_HARDWARE_CURSORS,1"
      echo "env = LIBVA_DRIVER_NAME,nvidia"
      echo "env = GBM_BACKEND,nvidia-drm"
      echo "env = __GLX_VENDOR_LIBRARY_NAME,nvidia"
      echo "env = NVD_BACKEND,direct"
      ;;
    amd)
      echo "env = WLR_NO_HARDWARE_CURSORS,0"
      echo "env = LIBVA_DRIVER_NAME,radeonsi"
      echo "env = GBM_BACKEND,gbm"
      ;;
    intel)
      echo "env = WLR_NO_HARDWARE_CURSORS,0"
      echo "env = LIBVA_DRIVER_NAME,i965"
      echo "env = GBM_BACKEND,gbm"
      ;;
    vm|*)
      echo "env = WLR_NO_HARDWARE_CURSORS,1"
      echo "env = GBM_BACKEND,gbm"
      ;;
  esac

  if $VM; then
    echo ""
    echo "# VM-specific"
    echo "env = HYPRLAND_VM,1"
  fi
} > "$GPU_CONF"

echo "hyprland-gpu-detect: wrote $GPU_CONF (GPU=$GPU, VM=$VM)" | logger -t hyprland-gpu
