MODULES=(vmw_vmci vmw_vsock_vmci_transport vmwgfx vmw_balloon
         vboxguest vboxsf vboxvideo
         virtio virtio_pci virtio_net virtio_blk virtio_scsi
         virtio_balloon virtio_rng virtio_input virtio_serio
         virtio_console virtio_gpu virtio_vsock virtio_fs virtio_crypto
         qxl bochs_drm
         nvidia nvidia_modeset nvidia_uvm nvidia_drm
         amdgpu radeon i915)
BINARIES=(vmware-rpctool vmtoolsd VBoxService qemu-ga spice-vdagent)
FILES=(/etc/udev/rules.d/99-vm-guest.rules)
HOOKS=(base udev autodetect modconf kms keyboard keymap consolefont block plymouth archiso_loop_mnt archiso_pxe_common archiso_pxe_nbd archiso_pxe_http archiso_pxe_nfs filesystems resume fsck)
