#!/usr/bin/env bash
# /home/aiuser/.config/hypr/scripts/gpu-detect.sh
# Detects GPU vendor and VM status, writes GPU env vars to
# ~/.config/hypr/env/gpu.conf for inclusion by hyprland.conf

set -euo pipefail

GPU_CONF="$HOME/.config/hypr/env/gpu.conf"
mkdir -p "$(dirname "$GPU_CONF")"

detect_vm() {
  if systemd-detect-virt --vm --quiet 2>/dev/null; then
    return 0
  fi
  if grep -qi "hypervisor" /proc/cpuinfo 2>/dev/null; then
    return 0
  fi
  return 1
}

detect_gpu() {
  local gpu_info
  gpu_info=$(lspci 2>/dev/null | grep -iE "(vga|3d|display)" || echo "")

  if echo "$gpu_info" | grep -qi "nvidia"; then
    echo "nvidia"
  elif echo "$gpu_info" | grep -qi "amd" || echo "$gpu_info" | grep -qi "advanced micro devices"; then
    echo "amd"
  elif echo "$gpu_info" | grep -qi "intel"; then
    echo "intel"
  elif echo "$gpu_info" | grep -qi "virtio"; then
    echo "virtio"
  elif echo "$gpu_info" | grep -qi "qxl" || echo "$gpu_info" | grep -qi "cirrus" || echo "$gpu_info" | grep -qi "vmware" || echo "$gpu_info" | grep -qi "vbox"; then
    echo "vm"
  else
    echo "unknown"
  fi
}

cat > "$GPU_CONF" << 'ENVHEADER'
# GPU environment variables — auto-generated by gpu-detect.sh
# This file is sourced by hyprland.conf
ENVHEADER

GPU=$(detect_gpu)
VM=false
detect_vm && VM=true

case "$GPU" in
  nvidia)
    cat >> "$GPU_CONF" << 'NVIDIA'
env = WLR_NO_HARDWARE_CURSORS,1
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
NVIDIA
    ;;
  amd)
    cat >> "$GPU_CONF" << 'AMD'
env = WLR_NO_HARDWARE_CURSORS,0
env = LIBVA_DRIVER_NAME,radeonsi
env = GBM_BACKEND,gbm
AMD
    ;;
  intel)
    cat >> "$GPU_CONF" << 'INTEL'
env = WLR_NO_HARDWARE_CURSORS,0
env = LIBVA_DRIVER_NAME,i965
env = GBM_BACKEND,gbm
INTEL
    ;;
  virtio|vm)
    cat >> "$GPU_CONF" << 'VMGPU'
env = WLR_NO_HARDWARE_CURSORS,1
env = GBM_BACKEND,gbm
VMGPU
    ;;
  *)
    cat >> "$GPU_CONF" << 'UNKNOWN'
env = WLR_NO_HARDWARE_CURSORS,1
UNKNOWN
    ;;
esac

if $VM; then
  cat >> "$GPU_CONF" << 'VMSETTINGS'

# VM-specific env vars and tweaks
env = HYPRLAND_VM,1
VMSETTINGS
fi

echo "gpu-detect: wrote $GPU_CONF (GPU=$GPU, VM=$VM)" | logger -t hyprland-gpu
