# /etc/systemd/resolved.conf.d/iso-dns.conf
[Resolve]
DNSOverTLS=opportunistic
DNSSEC=allow-downgrade
LLMNR=yes
MulticastDNS=yes
DNSStubListener=yes
DNSStubListenerExtra=127.0.0.53
FallbackDNS=1.1.1.1 8.8.8.8 2606:4700:4700::1111 2001:4860:4860::8888